server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/online_food_diary
    username: postgres
    password: 123654789et
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true